---
# PLUGINS
# ==========================================

# Startup
# -------
- repo: Shougo/dein.vim

- repo: vimwiki/vimwiki
  if: empty($VIM_MINIMAL)
  on_map: { n: <Plug> }
  on_cmd: Vimwiki
  hook_add: |
    let g:vimwiki_use_calendar = 1
    let g:vimwiki_hl_headers = 1
    let g:vimwiki_hl_cb_checked = 1
    let g:vimwiki_autowriteall = 0
  hook_source: source $VIMPATH/config/plugins/vimwiki.vim
